version: "3"
services:

  nodeapp:
    container_name: f10a25865b5f
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mongodb://db:27017/posts 
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
  
  mongodb:
    container_name: 4ddc97655d7d
    image: mongo:4.4.6
    restart: always
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"

    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge