version: "3"
services:
  
  mongodb:
    container_name: 4ddc97655d7d
    image: mongo
    # restart: always
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"

  nodeapp:
    container_name: f10a25865b5f
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mongodb://mongodb:27017/posts 
    ports:
      - "80:3000"
    links:
      - mongodb

#     networks:
#       - node-webapp-network
# networks:
#   node-webapp-network:
#     driver: bridge